
---
- name: Initialize Kubernetes Master Node and Get Join Token
  hosts: master-node
  become: yes
  tasks:
    - name: Check if Kubernetes master is already initialized
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: kube_admin_conf

    - name: Initialize Kubernetes cluster
      ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ hostvars['master-node']['ansible_host'] }}
      when: not kube_admin_conf.stat.exists

    - name: Get home directory of the user that invoked sudo
      ansible.builtin.command: echo $HOME
      register: user_home_dir
      changed_when: false
      become: no

    - name: Create .kube directory for current user
      ansible.builtin.file:
        path: "{{ user_home_dir.stdout }}/.kube"
        state: directory
        mode: '0755'
      become: no

    - name: Copy admin.conf to current user's .kube directory and set ownership
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ user_home_dir.stdout }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: '0644'

    - name: Get kubeadm join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: kubeadm_join_command_output
      changed_when: false

    - name: Save kubeadm join command to file on Ansible controller
      ansible.builtin.copy:
        content: "{{ kubeadm_join_command_output.stdout }}"
        dest: "{{ playbook_dir }}/../kubeadm_join_command.txt"
        mode: '0644'
      delegate_to: localhost
      run_once: true
      become: no
